cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),

]

hoodie_lab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('products.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.product_list, name="home"),
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models

class Size(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name

class Hoodie(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200)
    details = models.TextField(max_length=300,
                               blank=True)
    color = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=10, 
                                decimal_places=2)
    image = models.ImageField(upload_to='products/',
                              blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name
    

class HoodieSize(models.Model):
    hoodie = models.ForeignKey(Hoodie,
                               on_delete=models.CASCADE)
    size = models.ForeignKey(Size,
                             on_delete=models.CASCADE)
    stock = models.IntegerField(default=0)   
    available = models.BooleanField(default=False) 

    def __str__(self):
        return f'{self.hoodie.name} | Size: {self.size.name} | Stock: {self.stock}'

cart/forms.py
from django import forms

SIZES = (
    ('XS', 'XS'),
    ('S', 'S'),
    ('M', 'M'),
    ('L', 'L'),
    ('XL', 'XL'),
)

class CartAddProductForm(forms.Form):
    Rozmiar = forms.TypedChoiceField(choices=SIZES)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from products.models import Hoodie
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Hoodie, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cart.add(product=product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request,
                  'cart/detail.html',
                  {'cart': cart})
    

products/views.py
from django.shortcuts import render, get_object_or_404
from .models import Hoodie
from cart.forms import CartAddProductForm

def product_list(request):
    products = Hoodie.objects.all()
    return render(request,
                  'products/product_list.html',
                  {'products': products})

def product_detail(request, slug):
    product = get_object_or_404(Hoodie,
                                slug=slug)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'products/product_detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form},)

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Koszyk
{% endblock %}

{% block content %}
<section class="h-screen py-12 sm:py-16 lg:py-20">
    <div class="mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex items-center justify-center">
        <h1 class="text-2xl font-semibold text-gray-900">Koszyk</h1>
      </div>
  
      <div class="mx-auto mt-8 max-w-2xl md:mt-12">
        <div class="bg-white shadow">
          <div class="px-4 py-6 sm:px-8 sm:py-10">
            <div class="flow-root">
              <ul class="-my-8">
                {% for item in cart %}
                    {% with product=item.product %}
                <li class="flex flex-col space-y-3 py-6 text-left sm:flex-row sm:space-x-5 sm:space-y-0">
                  <div class="shrink-0">
                    <img class="h-24 w-24 max-w-full rounded-lg object-cover" src="{% if product.image %}{{ product.image.url }}{% else %}{% get_media_prefix %}products/no-image.jpg{% endif %}" alt="{{ product.name }}" />
                  </div>
  
                  <div class="relative flex flex-1 flex-col justify-between">
                    <div class="sm:col-gap-5 sm:grid sm:grid-cols-2">
                      <div class="pr-8 sm:pr-5">
                        <p class="text-base font-semibold text-gray-900">{{ product.name }}</p>
                        <p class="mx-0 mt-1 mb-0 text-sm text-gray-400">{{ product.size }}</p>
                      </div>
  
                      <div class="mt-4 flex items-end justify-between sm:mt-0 sm:items-start sm:justify-end">
                        <p class="shrink-0 w-20 text-base font-semibold text-gray-900 sm:order-2 sm:ml-8 sm:text-right">{{ product.price }} zł</p>
  
                      </div>
                    </div>
  
                    <div class="absolute top-0 right-0 flex sm:bottom-0 sm:top-auto">
                      <button type="button" class="flex rounded p-2 text-center text-gray-500 transition-all duration-200 ease-in-out focus:shadow hover:text-gray-900">
                        <svg class="block h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" class=""></path>
                        </svg>
                      </button>
                    </div>
                  </div>
                </li>
                {% endwith %}
                {% endfor %}
              </ul>
            </div>
  
            <div class="mt-6 border-t border-b py-2">
              <div class="flex items-center justify-between">
                <p class="text-sm text-gray-400">Subtotal</p>
                <p class="text-lg font-semibold text-gray-900">$399.00</p>
              </div>
              <div class="flex items-center justify-between">
                <p class="text-sm text-gray-400">Shipping</p>
                <p class="text-lg font-semibold text-gray-900">$8.00</p>
              </div>
            </div>
            <div class="mt-6 flex items-center justify-between">
              <p class="text-sm font-medium text-gray-900">Total</p>
              <p class="text-2xl font-semibold text-gray-900"><span class="text-xs font-normal text-gray-400">USD</span> 408.00</p>
            </div>
  
            <div class="mt-6 text-center">
              <button type="button" class="group inline-flex w-full items-center justify-center rounded-md bg-gray-900 px-6 py-4 text-lg font-semibold text-white transition-all duration-200 ease-in-out focus:shadow hover:bg-gray-800">
                Checkout
                <svg xmlns="http://www.w3.org/2000/svg" class="group-hover:ml-8 ml-4 h-6 w-6 transition-all" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M13 7l5 5m0 0l-5 5m5-5H6" />
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}
  

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
<section class="text-gray-700 body-font overflow-hidden bg-white">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <img class="lg:w-1/2 w-full object-cover object-center rounded border border-gray-200" src="{% if product.image %}{{ product.image.url }}{% else %}{% get_media_prefix %}products/no-image.jpg{% endif %}" alt="{{ product.name }}">
        <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-1">{{ product.name }}</h1>
          <p class="leading-relaxed">{{ product.details}}</p>
          <div class="flex mt-6 items-center pb-5 border-b-2 border-gray-200 mb-5">
            <div class="flex">
              <span class="mr-3">Kolor: {{ product.color }}</span>
            </div>
            <form action="{% url "cart:cart_add" product.id %}" method="POST">
                {% csrf_token %}
            <div class="flex ml-6 items-center">
              <div class="relative">
                {{ cart_product_form }}
                <span class="absolute right-0 top-0 h-full w-10 text-center text-gray-600 pointer-events-none flex items-center justify-center">
                  <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4" viewBox="0 0 24 24">
                    <path d="M6 9l6 6 6-6"></path>
                  </svg>
                </span>
              </div>
            </div>
      
          </div>
          <div class="flex">
            <span class="title-font font-medium text-2xl text-gray-900">{{ product.price }} zł</span>
            <input type="submit" class="flex ml-auto text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded cursor-pointer" value="Dodaj do koszyka"/>
          </div>
        </form>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

products/templates/products/product_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Strona główna
{% endblock %}

{% block content %}
<div class="bg-white">
    <div class="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-10 lg:max-w-7xl lg:px-8">
      
      <div class="grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
        {% for product in products %}
        <div class="group relative">
          <div class="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-md bg-gray-200 lg:aspect-none group-hover:opacity-75 lg:h-80">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% get_media_prefix %}products/no-image.jpg{% endif %}" alt="{{ product.name }}" class="h-full w-full object-cover object-center lg:h-full lg:w-full">
          </div>
          <div class="mt-4 flex justify-between">
            <div>
              <h3 class="text-sm text-gray-700">
                <a href="{% url "product_detail" product.slug %}">
                  <span aria-hidden="true" class="absolute inset-0"></span>
                  {{ product.name }}
                </a>
              </h3>
              <p class="mt-1 text-sm text-gray-500">{{ product.color }}</p>
            </div>
            <p class="text-sm font-medium text-gray-900">{{ product.price }} zł</p>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>{% block title %}Home page{% endblock %}</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<nav class="relative flex w-full flex-wrap items-center justify-between py-2 text-neutral-500 shadow-lg hover:text-neutral-700 focus:text-neutral-700 bg-teal-800 lg:py-4">
		<div class="flex w-full flex-wrap items-center justify-between px-3">
		  <div class="ml-2">
			<a
			  class="text-xl text-neutral-100 font-sans font-bold"
			  href="{% url "home" %}"
			  >HOODIE LAB</a
			>
		  </div>
		<div class="relative flex items-center">
			<a
			class="ml-1 text-neutral-500 transition duration-200 hover:text-neutral-700 hover:ease-in-out focus:text-neutral-700 disabled:text-black/30 motion-reduce:transition-none dark:text-neutral-200 dark:hover:text-neutral-300 dark:focus:text-neutral-300 [&.active]:text-black/90 dark:[&.active]:text-neutral-400"
			href="{% url "cart:cart_detail" %}">
			<div class="mr-2">
			<span class="[&>svg]:w-5">
			  <svg
				xmlns="http://www.w3.org/2000/svg"
				viewBox="0 0 24 24"
				fill="currentColor"
				class="h-5 w-5">
				<path
				  d="M2.25 2.25a.75.75 0 000 1.5h1.386c.17 0 .318.114.362.278l2.558 9.592a3.752 3.752 0 00-2.806 3.63c0 .414.336.75.75.75h15.75a.75.75 0 000-1.5H5.378A2.25 2.25 0 017.5 15h11.218a.75.75 0 00.674-.421 60.358 60.358 0 002.96-7.228.75.75 0 00-.525-.965A60.864 60.864 0 005.68 4.509l-.232-.867A1.875 1.875 0 003.636 2.25H2.25zM3.75 20.25a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0zM16.5 20.25a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0z" />
			  </svg>
			</span>
		</div>
		  </a>
		</div
		</div>

		
	  </nav>
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				{% block content %}
				{% endblock %}
			</section>
		</div>
	</body>
</html>